#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use FlightTracker\Command\FlightTrackerCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new FlightTrackerCommand());
$application->run();
